// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArM7YcoP1BdoVf-RyMqoH61bDs5V-yshI',
    appId: '1:185349118973:web:fa6c284f35babd0a5d5794',
    messagingSenderId: '185349118973',
    projectId: 'final-eng-track',
    authDomain: 'final-eng-track.firebaseapp.com',
    storageBucket: 'final-eng-track.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13ZQFdHLTQD7B9BES_25cHXpoULlFL3w',
    appId: '1:185349118973:android:d06f1866cb3e5df95d5794',
    messagingSenderId: '185349118973',
    projectId: 'final-eng-track',
    storageBucket: 'final-eng-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYo9qrB6J-g3Vcoq5WZW9Z4A-DXeMlIo8',
    appId: '1:185349118973:ios:785ccc0c4824c3255d5794',
    messagingSenderId: '185349118973',
    projectId: 'final-eng-track',
    storageBucket: 'final-eng-track.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYo9qrB6J-g3Vcoq5WZW9Z4A-DXeMlIo8',
    appId: '1:185349118973:ios:785ccc0c4824c3255d5794',
    messagingSenderId: '185349118973',
    projectId: 'final-eng-track',
    storageBucket: 'final-eng-track.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArM7YcoP1BdoVf-RyMqoH61bDs5V-yshI',
    appId: '1:185349118973:web:2c37fdad37abe42d5d5794',
    messagingSenderId: '185349118973',
    projectId: 'final-eng-track',
    authDomain: 'final-eng-track.firebaseapp.com',
    storageBucket: 'final-eng-track.appspot.com',
  );

}